apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
spec:
  selector:
    matchLabels:
      app: mysql
  replicas: 1
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
        - name: mysql
          image: mysql:5.7
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: "your_root_password"    # Change this password to a secure value
            - name: MYSQL_DATABASE
              value: "mydatabase"           # Optional: Specify a database name to create on startup
            - name: MYSQL_USER
              value: "myuser"               # Optional: Specify a user name for the database
            - name: MYSQL_PASSWORD
              value: "mypassword"           # Optional: Specify a password for the user
          ports:
            - containerPort: 3306
          volumeMounts:
            - name: mysql-storage
              mountPath: /var/lib/mysql       # MySQL data directory
      volumes:
        - name: mysql-storage
          persistentVolumeClaim:
            claimName: mysql-pvc       # Use the correct PVC name

---

apiVersion: v1
kind: Service
metadata:
  name: mysql
spec:
  type: ClusterIP
  ports:
    - port: 3306
      targetPort: 3306
      protocol: TCP
  selector:
    app: mysql
