## Creation of mongo DB with Azure disk as PV and deployment using stateful set


apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mongodb
  namespace: production
spec:
  serviceName: mongodb-headless
  replicas: 1
  selector:
    matchLabels:
      app: mongodb
  template:
    metadata:
      labels:
        app: mongodb
    spec:
      containers:
        - name: mongodb
          image: mongo:6.0
          env:
            - name: MONGO_INITDB_ROOT_USERNAME
              valueFrom:
                secretKeyRef:
                  name: mongodb-chat-prod-secret
                  key: MONGO_INITDB_ROOT_USERNAME
            - name: MONGO_INITDB_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mongodb-chat-prod-secret
                  key: MONGO_INITDB_ROOT_PASSWORD
          ports:
            - containerPort: 27017
          volumeMounts:
            - name: mongodb-data
              mountPath: /data/db
  volumeClaimTemplates:
    - metadata:
        name: mongodb-data
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 10Gi          # Customize storage size as needed

---

apiVersion: v1
kind: Service
metadata:
  name: mongodb
  namespace: production
spec:
  ports:
    - port: 27017
      targetPort: 27017
      protocol: TCP
  selector:
    app: mongodb
  type: ClusterIP

---

apiVersion: v1
kind: Service
metadata:
  name: mongodb-headless
  namespace: production
spec:
  ports:
    - port: 27017
      targetPort: 27017
  clusterIP: None
  selector:
    app: mongodb

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: mongodb-pv
  namespace: production
spec:
  capacity:
    storage: 10Gi                              # Updated storage capacity
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: default
  azureDisk:                                   # Azure Disk for persistent storage
    diskName: "mongodb-storage-prod"
    diskURI: "/subscriptions/xxxxxx45b4-46e0-xxxxxxx7d2f/resourcegroups/xxxxxxxxxx/providers/Microsoft.Compute/disks/mongodb-storage-prod"
    kind: Managed

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongodb-pvc
  namespace: production
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi                            # Match storage size with PV
  volumeName: mongodb-pv                       # Bind to the specific PersistentVolume
  storageClassName: default
