## use this to encode password fields [echo -n "staging-db-password" | base64 ]
## echo -n "TEST@234" | base64 | tr -d '\n' # new line protection


apiVersion: v1
kind: Secret
metadata:
  name: chat-app-secret-prod
  namespace: production
type: Opaque
data:
  MONGODB_URI: "bW9uZ29kYitzcnY6Ly9hZG1pbjpwOWFCN0Z5U1QyNXJRbkBjaGF0YXBwLXByb2QuZjNtbDYubW9uZ29kYi5uZXQ="  # Variable for docker-compose file
