apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-config
  namespace: {{ .Values.namespace }}
data:
  NODE_ENV: {{ .Values.backend.env.NODE_ENV }}
  PORT: {{ .Values.backend.env.PORT }}
  CORS_ORIGIN: {{ .Values.backend.env.CORS_ORIGIN }}
