apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-secret
  namespace: {{ .Values.namespace }}
type: Opaque
data:
  MONGODB_URI: {{ .Values.secrets.MONGODB_URI }}



apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secret.name }}
  namespace: {{ .Values.namespace }}
type: Opaque
data:
  MONGO_INITDB_ROOT_USERNAME: {{ .Values.secret.mongoRootUsername }}
  MONGO_INITDB_ROOT_PASSWORD: {{ .Values.secret.mongoRootPassword }}
  MONGO_CONNECTION_STRING: {{ .Values.secret.mongoConnectionString }}
