# chat-app-backend-lb-service.yaml
apiVersion: v1
kind: Service
metadata:
  name: chat-app-backend-loadbalancer
  annotations:
    kubernetes.digitalocean.com/load-balancer-id: "chat-app-backend-lb"
    service.beta.kubernetes.io/do-loadbalancer-size-unit: "1"
    service.beta.kubernetes.io/do-loadbalancer-disable-lets-encrypt-dns-records: "false"
spec:
  type: LoadBalancer
  selector:
    app: chat-app
    tier: backend
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 8080