# chat-app-frontend-lb-service.yaml
apiVersion: v1
kind: Service
metadata:
  name: chat-app-frontend-loadbalancer
  annotations:
    kubernetes.digitalocean.com/load-balancer-id: "chat-app-frontend-lb"
    service.beta.kubernetes.io/do-loadbalancer-size-unit: "1"
    service.beta.kubernetes.io/do-loadbalancer-disable-lets-encrypt-dns-records: "false"
spec:
  type: LoadBalancer
  selector:
    app: chat-app-frontend
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 3000