apiVersion: v1
kind: Service
metadata:
  name: chat-app-backend-nodeport
spec:
  type: NodePort
  selector:
    app: chat-app
    tier: backend
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 32000  # You can specify a particular nodePort or let Kubernetes assign one in the range 30000-32767