apiVersion: v1
kind: Service
metadata:
  name: chat-app-frontend-nodeport
spec:
  type: NodePort
  selector:
    app: chat-app-frontend
  ports:
    - port: 3000
      targetPort: 3000
      nodePort: 31000  # You can specify a particular nodePort or let Kubernetes assign one in the range 30000-32767