# echo -n "admin" | base64
# echo -n "password123" | base64

apiVersion: v1
kind: Secret
metadata:
  name: mongodb-chat-prod-secret
  namespace: production
type: Opaque
data:
  MONGO_INITDB_ROOT_USERNAME: YWRtaW4=
  MONGO_INITDB_ROOT_PASSWORD: cGFzc3dvcmQxMjM=
  MONGO_CONNECTION_STRING: XxxxxX                     #echo -n "mongodb://admin:password123@mongodb-service.mongodb.svc.cluster.local:27017" | base64

---


apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mongodb-chat-prod
  namespace: production
spec:
  serviceName: "mongodb-svc"
  replicas: 1
  selector:
    matchLabels:
      app: mongodb-chat-prod
  template:
    metadata:
      labels:
        app: mongodb-chat-prod
    spec:
      containers:
        - name: mongodb-chat-prod
          image: mongo:6.0
          ports:
            - containerPort: 27017
          env:
            - name: MONGO_INITDB_ROOT_USERNAME
              valueFrom:
                secretKeyRef:
                  name: mongodb-chat-prod-secret
                  key: MONGO_INITDB_ROOT_USERNAME
            - name: MONGO_INITDB_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mongodb-chat-prod-secret
                  key: MONGO_INITDB_ROOT_PASSWORD
          volumeMounts:
            - name: mongodb-chat-storage
              mountPath: /data/db
  volumeClaimTemplates:
    - metadata:
        name: mongodb-chat-storage
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 10Gi
        storageClassName: ebs-sc

---
# DB Svc
apiVersion: v1
kind: Service
metadata:
  name: mongodb-service
  namespace: mongodb
spec:
  ports:
    - port: 27017
  selector:
    app: mongodb
  clusterIP: None # For StatefulSet


---
# EBS Stotage Class Define  

apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: ebs-sc
provisioner: ebs.csi.aws.com
volumeBindingMode: WaitForFirstConsumer


---

# EBS PV
apiVersion: v1
kind: PersistentVolume
metadata:
  name: mongodb-pv
spec:
  capacity:
    storage: 10Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ebs-sc
  csi:
    driver: ebs.csi.aws.com
    volumeHandle: <EBS_VOLUME_ID> # Replace with your EBS volume ID

---
# EBS PVC

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongodb-pvc
  namespace: mongodb
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: ebs-sc

