name: Build and Push Docker Images

on:
  push:
    tags:
      - "v*"  # Trigger only on tag creation

jobs:
  build-and-push:
    name: Build and Push Docker Images
    runs-on: ubuntu-latest

    env:
      REGISTRY: docker.io   # Docker Hub registry
      BACKEND_IMAGE_NAME: noscopev6/chatapp-b    # Image name for the backend

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Log in to Container Registry
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}

      - name: Build and Push Backend Image
        working-directory: chatapp-backend
        run: |
          docker build -t ${{ env.REGISTRY }}/${{ env.BACKEND_IMAGE_NAME }}:${{ github.ref_name }} .
          docker push ${{ env.REGISTRY }}/${{ env.BACKEND_IMAGE_NAME }}:${{ github.ref_name }}
